/* Linux Commands Keeper - Initial Setup */
-- Create database
CREATE DATABASE linux_commands;

-- Use the database
USE linux_commands;

--
-- Table structure for table `Linux commands`
--

-- Table structure for table `linux_commands`
CREATE TABLE linux_commands (
    id INT AUTO_INCREMENT PRIMARY KEY,
    command TEXT NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(255) NOT NULL,
    example TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INSERT INTO linux_commands (command, description, category, example) VALUES
-- ('pwd', 'Prints the current working directory.', 'Basic Navigation and File Management', 'pwd'),
-- ('ls', 'Lists files and directories.', 'Basic Navigation and File Management', 'ls -l'),
-- ('cd', 'Changes the current directory.', 'Basic Navigation and File Management', 'cd /home/user'),
-- ('mkdir', 'Creates a new directory.', 'Basic Navigation and File Management', 'mkdir new_folder'),
-- ('rmdir', 'Removes an empty directory.', 'Basic Navigation and File Management', 'rmdir old_folder'),
-- ('rm', 'Removes files or directories.', 'Basic Navigation and File Management', 'rm -rf folder_name'),
-- ('cp', 'Copies files or directories.', 'Basic Navigation and File Management', 'cp file1.txt file2.txt'),
-- ('mv', 'Moves or renames files or directories.', 'Basic Navigation and File Management', 'mv old.txt new.txt'),
-- ('find', 'Searches for files and directories.', 'Basic Navigation and File Management', 'find / -name "file.txt"'),
-- ('locate', 'Finds files by name.', 'Basic Navigation and File Management', 'locate file.txt'),
-- ('touch', 'Creates an empty file or updates a file timestamp.', 'Basic Navigation and File Management', 'touch newfile.txt'),
-- ('tree', 'Displays directories in a tree-like format.', 'Basic Navigation and File Management', 'tree /home'),
-- ('basename', 'Extracts the filename from a path.', 'Basic Navigation and File Management', 'basename /home/user/file.txt'),
-- ('dirname', 'Extracts the directory from a path.', 'Basic Navigation and File Management', 'dirname /home/user/file.txt'),
-- ('realpath', 'Prints the absolute path of a file.', 'Basic Navigation and File Management', 'realpath file.txt'),
-- ('stat', 'Displays detailed file information.', 'Basic Navigation and File Management', 'stat file.txt'),
-- ('readlink', 'Displays the target of a symbolic link.', 'Basic Navigation and File Management', 'readlink symlink'),
-- ('file', 'Determines the type of a file.', 'Basic Navigation and File Management', 'file document.pdf'),
-- ('ln', 'Creates a symbolic or hard link.', 'Basic Navigation and File Management', 'ln -s original.txt link.txt'),
-- ('alias', 'Creates a shortcut for a command.', 'Basic Navigation and File Management', 'alias ll="ls -la"'),
-- ('cat', 'Concatenates and displays file contents.', 'Viewing and Editing Files', 'cat file.txt'),
-- ('less', 'Views file contents one page at a time.', 'Viewing and Editing Files', 'less file.txt'),
-- ('more', 'Similar to less but with fewer features.', 'Viewing and Editing Files', 'more file.txt'),
-- ('head', 'Displays the first few lines of a file.', 'Viewing and Editing Files', 'head -n 10 file.txt'),
-- ('tail', 'Displays the last few lines of a file.', 'Viewing and Editing Files', 'tail -n 10 file.txt');




INSERT INTO linux_commands (command, description, category, example) VALUES
('pwd', 'Print working directory', 'Basic Navigation and File Management', NULL),
('ls', 'List directory contents', 'Basic Navigation and File Management', 'ls -l'),
('cd', 'Change directory', 'Basic Navigation and File Management', 'cd /home/user'),
('mkdir', 'Create a directory', 'Basic Navigation and File Management', 'mkdir new_dir'),
('rmdir', 'Remove empty directories', 'Basic Navigation and File Management', 'rmdir empty_dir'),
('rm', 'Remove files or directories', 'Basic Navigation and File Management', 'rm file.txt'),
('cp', 'Copy files or directories', 'Basic Navigation and File Management', 'cp file1.txt file2.txt'),
('mv', 'Move or rename files or directories', 'Basic Navigation and File Management', 'mv file.txt new_file.txt'),
('find', 'Search for files in a directory hierarchy', 'Basic Navigation and File Management', 'find / -name file.txt'),
('locate', 'Find files by name', 'Basic Navigation and File Management', 'locate file.txt'),
('touch', 'Change file timestamps or create empty files', 'Basic Navigation and File Management', 'touch new_file.txt'),
('tree', 'List contents of directories in a tree-like format', 'Basic Navigation and File Management', 'tree /home/user'),
('basename', 'Strip directory and suffix from filenames', 'Basic Navigation and File Management', 'basename /path/to/file.txt'),
('dirname', 'Strip last component from file name', 'Basic Navigation and File Management', 'dirname /path/to/file.txt'),
('realpath', 'Return the canonicalized absolute pathname', 'Basic Navigation and File Management', 'realpath file.txt'),
('stat', 'Display file or file system status', 'Basic Navigation and File Management', 'stat file.txt'),
('readlink', 'Print value of a symbolic link', 'Basic Navigation and File Management', 'readlink symlink'),
('file', 'Determine file type', 'Basic Navigation and File Management', 'file file.txt'),
('ln', 'Make links between files', 'Basic Navigation and File Management', 'ln -s file.txt symlink'),
('alias', 'Create or display aliases', 'Basic Navigation and File Management', 'alias ll="ls -l"'),
('cat', 'Concatenate files and print on the standard output', 'Viewing and Editing Files', 'cat file.txt'),
('less', 'View file contents one screen at a time', 'Viewing and Editing Files', 'less file.txt'),
('more', 'View file contents one screen at a time', 'Viewing and Editing Files', 'more file.txt'),
('head', 'Output the first part of files', 'Viewing and Editing Files', 'head -n 10 file.txt'),
('tail', 'Output the last part of files', 'Viewing and Editing Files', 'tail -n 10 file.txt'),
('nano', 'Simple text editor', 'Viewing and Editing Files', 'nano file.txt'),
('vim', 'Advanced text editor', 'Viewing and Editing Files', 'vim file.txt'),
('gedit', 'GUI text editor', 'Viewing and Editing Files', 'gedit file.txt'),
('emacs', 'Advanced text editor', 'Viewing and Editing Files', 'emacs file.txt'),
('echo', 'Display a line of text', 'Viewing and Editing Files', 'echo "Hello, world!"'),
('wc', 'Print newline, word, and byte counts for each file', 'Viewing and Editing Files', 'wc file.txt'),
('cut', 'Remove sections from each line of files', 'Viewing and Editing Files', 'cut -d "," -f1 file.csv'),
('split', 'Split a file into pieces', 'Viewing and Editing Files', 'split -l 100 file.txt'),
('cmp', 'Compare two files byte by byte', 'Viewing and Editing Files', 'cmp file1.txt file2.txt'),
('diff', 'Compare files line by line', 'Viewing and Editing Files', 'diff file1.txt file2.txt'),
('patch', 'Apply a diff file to an original', 'Viewing and Editing Files', 'patch file.txt diff.patch'),
('sort', 'Sort lines of text files', 'Viewing and Editing Files', 'sort file.txt'),
('uniq', 'Report or omit repeated lines', 'Viewing and Editing Files', 'uniq file.txt'),
('tr', 'Translate or delete characters', 'Viewing and Editing Files', 'tr "a-z" "A-Z" < file.txt'),
('sed', 'Stream editor for filtering and transforming text', 'Viewing and Editing Files', 'sed "s/old/new/g" file.txt'),
('chmod', 'Change file mode bits', 'Permissions and Ownership', 'chmod +x script.sh'),
('chown', 'Change file owner and group', 'Permissions and Ownership', 'chown user:group file.txt'),
('chgrp', 'Change group ownership', 'Permissions and Ownership', 'chgrp group file.txt'),
('umask', 'Set file mode creation mask', 'Permissions and Ownership', 'umask 022'),
('ls -l', 'List detailed file information', 'Permissions and Ownership', 'ls -l file.txt'),
('id', 'Print user and group IDs', 'Permissions and Ownership', 'id user'),
('groups', 'Print the groups a user is in', 'Permissions and Ownership', 'groups user'),
('whoami', 'Print effective user ID', 'Permissions and Ownership', 'whoami'),
('sudo', 'Execute a command as another user', 'Permissions and Ownership', 'sudo apt-get update'),
('su', 'Change user ID or become superuser', 'Permissions and Ownership', 'su root'),
('top', 'Display Linux processes', 'System Monitoring and Processes', 'top'),
('htop', 'Interactive process viewer', 'System Monitoring and Processes', 'htop'),
('ps', 'Report a snapshot of the current processes', 'System Monitoring and Processes', 'ps aux'),
('kill', 'Terminate a process', 'System Monitoring and Processes', 'kill 1234'),
('killall', 'Kill processes by name', 'System Monitoring and Processes', 'killall firefox'),
('pkill', 'Kill processes by name or other attributes', 'System Monitoring and Processes', 'pkill firefox'),
('jobs', 'List active jobs', 'System Monitoring and Processes', 'jobs'),
('fg', 'Bring a job to the foreground', 'System Monitoring and Processes', 'fg %1'),
('bg', 'Send a job to the background', 'System Monitoring and Processes', 'bg %1'),
('nice', 'Run a command with modified scheduling priority', 'System Monitoring and Processes', 'nice -n 10 command'),
('renice', 'Alter priority of running processes', 'System Monitoring and Processes', 'renice -n 10 -p 1234'),
('uptime', 'Show how long the system has been running', 'System Monitoring and Processes', 'uptime'),
('free', 'Display amount of free and used memory', 'System Monitoring and Processes', 'free -m'),
('df', 'Report file system disk space usage', 'System Monitoring and Processes', 'df -h'),
('du', 'Estimate file space usage', 'System Monitoring and Processes', 'du -sh /home/user'),
('iostat', 'Report CPU and disk I/O statistics', 'System Monitoring and Processes', 'iostat'),
('vmstat', 'Report virtual memory statistics', 'System Monitoring and Processes', 'vmstat'),
('sar', 'Collect, report, or save system activity information', 'System Monitoring and Processes', 'sar -u'),
('watch', 'Execute a program periodically, showing output in fullscreen', 'System Monitoring and Processes', 'watch df -h'),
('time', 'Time a command', 'System Monitoring and Processes', 'time ls -l'),
('ping', 'Send ICMP ECHO_REQUEST to network hosts', 'Networking Commands', 'ping google.com'),
('curl', 'Transfer a URL', 'Networking Commands', 'curl google.com'),
('wget', 'Non-interactive network downloader', 'Networking Commands', 'wget https://example.com/file.txt'),
('ifconfig', 'Configure a network interface', 'Networking Commands', 'ifconfig eth0'),
('ip', 'Show / manipulate routing, devices, policy routing and tunnels', 'Networking Commands', 'ip addr show'),
('netstat', 'Print network connections, routing tables, interface statistics, masquerade connections, and multicast memberships', 'Networking Commands', 'netstat -tulnp'),
('ss', 'Socket statistics', 'Networking Commands', 'ss -tulnp'),
('nslookup', 'Query Internet name servers interactively', 'Networking Commands', 'nslookup google.com'),
('dig', 'DNS lookup utility', 'Networking Commands', 'dig google.com'),
('traceroute', 'Trace route to a network host', 'Networking Commands', 'traceroute google.com'),
('route', 'Show / manipulate the IP routing table', 'Networking Commands', 'route -n'),
('arp', 'Manipulate the system ARP cache', 'Networking Commands', 'arp -a'),
('tcpdump', 'Dump traffic on a network', 'Networking Commands', 'tcpdump -i eth0'),
('nmap', 'Network exploration tool and security scanner', 'Networking Commands', 'nmap google.com'),
('scp', 'Secure copy (remote file copy program)', 'Networking Commands', 'scp file.txt user@host:/path/'),
('rsync', 'Remote file synchronization', 'Networking Commands', 'rsync -avz file.txt user@host:/path/'),
('ftp', 'File Transfer Protocol client', 'Networking Commands', 'ftp host'),
('telnet', 'User interface to the TELNET protocol', 'Networking Commands', 'telnet host'),
('ssh', 'OpenSSH remote login client', 'Networking Commands', 'ssh user@host'),
('apt-get', 'APT package handling utility', 'Package Management', 'apt-get update'),
('apt', 'Advanced Package Tool', 'Package Management', 'apt install package'),
('yum', 'Yellowdog Updater, Modified', 'Package Management', 'yum install package'),
('dnf', 'Dandified YUM', 'Package Management', 'dnf install package'),
('pacman', 'Package manager utility for Arch Linux', 'Package Management', 'pacman -S package'),
('snap', 'Package manager for snap packages', 'Package Management', 'snap install package'),
('flatpak', 'Application deployment and package management for desktop Linux', 'Package Management', 'flatpak install package'),
('rpm', 'RPM Package Manager', 'Package Management', 'rpm -i package.rpm'),
('dpkg', 'Package manager for Debian', 'Package Management', 'dpkg -i package.deb'),
('brew', 'Homebrew package manager', 'Package Management', 'brew install package'),
('mount', 'Mount a filesystem', 'Disk and Storage Management', 'mount /dev/sdb1 /mnt'),
('umount', 'Unmount a filesystem', 'Disk and Storage Management', 'umount /mnt'),
('blkid', 'Locate/print block device attributes', 'Disk and Storage Management', 'blkid /dev/sdb1'),
('lsblk', 'List block devices', 'Disk and Storage Management', 'lsblk'),
('fdisk', 'Partition table manipulator for Linux', 'Disk and Storage Management', 'fdisk /dev/sdb'),
('parted', 'Partition manipulation program', 'Disk and Storage Management', 'parted /dev/sdb'),
('mkfs', 'Create a filesystem', 'Disk and Storage Management', 'mkfs.ext4 /dev/sdb1'),
('fsck', 'Check and repair a Linux filesystem', 'Disk and Storage Management', 'fsck /dev/sdb1'),
('tune2fs', 'Adjust tunable filesystem parameters on ext2/ext3/ext4 filesystems', 'Disk and Storage Management', 'tune2fs -l /dev/sdb1'),
('resize2fs', 'Resize an ext2/ext3/ext4 filesystem', 'Disk and Storage Management', 'resize2fs /dev/sdb1'),
('e2fsck', 'Check an ext2/ext3/ext4 filesystem', 'Disk and Storage Management', 'e2fsck /dev/sdb1'),
('lsattr', 'List file attributes on a Linux second extended filesystem', 'Disk and Storage Management', 'lsattr file.txt'),
('chattr', 'Change file attributes on a Linux second extended filesystem', 'Disk and Storage Management', 'chattr +i file.txt'),
('xfs_check', 'Check XFS filesystem consistency', 'Disk and Storage Management', 'xfs_check /dev/sdb1'),
('xfs_repair', 'Repair an XFS filesystem', 'Disk and Storage Management', 'xfs_repair /dev/sdb1'),
('btrfs', 'Btrfs filesystem management', 'Disk and Storage Management', 'btrfs filesystem df /mnt'),
('swapoff', 'Disable devices and files for swap space', 'Disk and Storage Management', 'swapoff /dev/sdb2'),
('swapon', 'Enable devices and files for swap space', 'Disk and Storage Management', 'swapon /dev/sdb2'),
('tar', 'An archiving utility', 'Archiving and Compression', 'tar -cvzf archive.tar.gz directory'),
('zip', 'Package and compress (archive) files', 'Archiving and Compression', 'zip archive.zip files'),
('unzip', 'Extract compressed files in a ZIP archive', 'Archiving and Compression', 'unzip archive.zip'),
('gzip', 'Compress or decompress files', 'Archiving and Compression', 'gzip file.txt'),
('gunzip', 'Decompress files created by gzip', 'Archiving and Compression', 'gunzip file.txt.gz'),
('bzip2', 'A block-sorting file compressor', 'Archiving and Compression', 'bzip2 file.txt'),
('bunzip2', 'A file compressor based on Burrows-Wheeler block sorting reversible transformation', 'Archiving and Compression', 'bunzip2 file.txt.bz2'),
('xz', 'File compression utility', 'Archiving and Compression', 'xz file.txt'),
('unxz', 'Decompress .xz files', 'Archiving and Compression', 'unxz file.txt.xz'),
('7z', 'High compression ratio file archiver', 'Archiving and Compression', '7z a archive.7z files'),
('p7zip', '7-Zip file archiver', 'Archiving and Compression', 'p7zip a archive.7z files'),
('rar', 'Archiver for rar files', 'Archiving and Compression', 'rar a archive.rar files'),
('unrar', 'Extract files from rar archives', 'Archiving and Compression', 'unrar x archive.rar'),
('ar', 'Create, modify, and extract from archives', 'Archiving and Compression', 'ar -tv archive.ar'),
('cpio', 'Copy files to and from archives', 'Archiving and Compression', 'cpio -ivt < archive.cpio'),
('zcat', 'Compress or expand files', 'Archiving and Compression', 'zcat file.gz'),
('zless', 'File perusal filter for crt viewing of compressed text', 'Archiving and Compression', 'zless file.gz'),
('lzma', 'A file compressor with high compression ratio', 'Archiving and Compression', 'lzma file.txt'),
('xzcat', 'Decompress files to standard output', 'Archiving and Compression', 'xzcat file.txt.xz'),
('tar -zxvf', 'Extract a tar.gz archive', 'Archiving and Compression', 'tar -zxvf archive.tar.gz'),
('adduser', 'Add a user to the system', 'User Management', 'adduser user'),
('useradd', 'Create a new user or update default new user information', 'User Management', 'useradd user'),
('usermod', 'Modify a user account', 'User Management', 'usermod -aG sudo user'),
('deluser', 'Remove a user or group from the system', 'User Management', 'deluser user'),
('userdel', 'Delete a user account and related files', 'User Management', 'userdel -r user'),
('passwd', 'Change a user\'s password', 'User Management', 'passwd user'),
('groupadd', 'Create a new group', 'User Management', 'groupadd group'),
('groupmod', 'Modify a group', 'User Management', 'groupmod -n new_group old_group'),
('groupdel', 'Delete a group', 'User Management', 'groupdel group'),
('who', 'Show who is logged on', 'User Management', 'who'),
('w', 'Show who is logged on and what they are doing', 'User Management', 'w'),
('finger', 'User information lookup program', 'User Management', 'finger user'),
('last', 'Show listing of last logged in users', 'User Management', 'last'),
('login', 'Begin a new session on the system', 'User Management', 'login user'),
('logout', 'Exit from a login shell', 'User Management', 'logout'),
('visudo', 'Edit the sudoers file', 'User Management', 'visudo'),
('man', 'An interface to the system reference manuals', 'Miscellaneous Useful Commands', 'man ls'),
('history', 'Display or manipulate the history list', 'Miscellaneous Useful Commands', 'history'),
('clear', 'Clear the terminal screen', 'Miscellaneous Useful Commands', 'clear'),
('date', 'Show or set the system date and time', 'Miscellaneous Useful Commands', 'date'),
('cal', 'Display a calendar', 'Miscellaneous Useful Commands', 'cal'),
('uptime', 'Show how long the system has been running', 'Miscellaneous Useful Commands', 'uptime'),
('uname', 'Print system information', 'Miscellaneous Useful Commands', 'uname -a'),
('hostname', 'Show or set the system\'s host name', 'Miscellaneous Useful Commands', 'hostname'),
('bc', 'An arbitrary precision calculator language', 'Miscellaneous Useful Commands', 'bc'),
('expr', 'Evaluate expressions', 'Miscellaneous Useful Commands', 'expr 1 + 1'),
('seq', 'Print a sequence of numbers', 'Miscellaneous Useful Commands', 'seq 1 10'),
('yes', 'Output a string repeatedly until killed', 'Miscellaneous Useful Commands', 'yes'),
('sleep', 'Delay for a specified amount of time', 'Miscellaneous Useful Commands', 'sleep 10'),
('shutdown', 'Bring the system down', 'Miscellaneous Useful Commands', 'shutdown -h now'),
('reboot', 'Restart the system', 'Miscellaneous Useful Commands', 'reboot'),
('poweroff', 'Power off the system', 'Miscellaneous Useful Commands', 'poweroff'),
('systemctl', 'Control the systemd system and service manager', 'Miscellaneous Useful Commands', 'systemctl status apache2'),
('journalctl', 'Query the systemd journal', 'Miscellaneous Useful Commands', 'journalctl -xe'),
('dmesg', 'Print or control the kernel ring buffer', 'Miscellaneous Useful Commands', 'dmesg'),
('env', 'Run a program in a modified environment', 'Miscellaneous Useful Commands', 'env'),
('export', 'Set environment variables', 'Miscellaneous Useful Commands', 'export VAR=value'),
('printenv', 'Print all or part of the environment', 'Miscellaneous Useful Commands', 'printenv VAR'),
('set', 'Set or unset shell options and positional parameters', 'Miscellaneous Useful Commands', 'set'),
('unset', 'Remove shell variables or functions', 'Miscellaneous Useful Commands', 'unset VAR'),
('declare', 'Declare variables and/or give them attributes', 'Miscellaneous Useful Commands', 'declare -x VAR=value'),
('type', 'Write a description of command type', 'Miscellaneous Useful Commands', 'type ls'),
('which', 'Locate a command', 'Miscellaneous Useful Commands', 'which ls'),
('whereis', 'Locate the binary, source, and manual page files for a command', 'Miscellaneous Useful Commands', 'whereis ls'),
('apropos', 'Search the manual page names and descriptions', 'Miscellaneous Useful Commands', 'apropos keyword'),
('whatis', 'Display one-line manual page descriptions', 'Miscellaneous Useful Commands', 'whatis ls'),
('updatedb', 'Update the locate database', 'Miscellaneous Useful Commands', 'sudo updatedb'),
('xargs', 'Build and execute command lines from standard input', 'Miscellaneous Useful Commands', 'find . -name "*.txt" | xargs grep "keyword"'),
('tee', 'Read from standard input and write to standard output and files', 'Miscellaneous Useful Commands', 'ls -l | tee output.txt'),
('grep', 'Print lines matching a pattern', 'Miscellaneous Useful Commands', 'grep "keyword" file.txt'),
('awk', 'Pattern scanning and processing language', 'Miscellaneous Useful Commands', 'awk \'{print $1}\' file.txt'),
('cut', 'Remove sections from each line of files', 'Miscellaneous Useful Commands', 'cut -d "," -f1 file.csv'),
('nohup', 'Run a command immune to hangups, with output to a non-tty', 'Miscellaneous Useful Commands', 'nohup command &');